/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alice' at '1/4/16 9:58 PM' with Gradle 2.6
 *
 * @author Alice, @date 1/4/16 9:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
